name: wajid
description: "Wajid is a community-driven app designed to help people find and return lost items."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fpdart: ^1.1.0
  skeletonizer: ^1.4.2
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  injectable: ^2.5.0
  get_it: ^8.0.2
  auto_route: ^9.2.2
  uuid: ^4.5.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  supabase_flutter: ^2.8.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0


flutter:
  uses-material-design: true

  assets:
     - dev.env
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900

